services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - 'POSTGRES_DB=popytka_by'
      - 'POSTGRES_PASSWORD=150798710'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
