spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/popytka_by
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jackson:
    time-zone: Europe/Moscow

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  token:
    signing:
      key: ${SECRET_KEY}
      ttl: ${TTL_KEY}
      refresh: ${REFRESH_TTL_KEY}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  cache:
    redis:
      key-prefix: ${KEY_PREFIX}
      time-to-live: ${TTL_MINUTES}
      max-attempts: ${MAX_ATTEMPTS}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080
  address: localhost

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}

